<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">


    <link name="base_link"></link>

    <joint name="base_footprint_joint" type="fixed">
        <parent link="base_link" />
        <child link="base_footprint" />
        <origin xyz="0 0 0" rpy="0 0 0" />
    </joint>

    <link name="base_footprint">
    </link>

    <joint name="chassis_joint" type="fixed">
        <parent link="base_link" />
        <child link="chassis" />
        <origin xyz="0 0 0" />
    </joint>

    <link name="chassis">
        <visual>
            <origin xyz="0 0 0.05" />
            <geometry>
                <box size="0.1 0.1 0.1" />
            </geometry>
            <material name="white" />
        </visual>
        <collision>
            <origin xyz="0 0 0" />
            <geometry>
                <box size="0.1 0.1 0.1" />
            </geometry>
        </collision>
        <xacro:inertial_box mass="0.5"
            x="0.1" y="0.1" z="0.1">
            <origin xyz="0 0 0.05" rpy="0 0 0" />
        </xacro:inertial_box>
    </link>

    <gazebo reference="chassis">
        <material>Gazebo/White</material>
    </gazebo>

    <joint name="lidar_joint" type="fixed">
        <parent link="base_link" />
        <child link="lidar_link" />
        <origin
            xyz="0 0 0.1"
            ryp="0 0 0" />
    </joint>

    <link name="lidar_link"></link>

    <xacro:lidar nameprefix="laser"
        parent="lidar_link"
        length="${lidar_length}"
        radius="${lidar_radius}"
        mass="${lidar_weight}">
        <origin xyz="0 0 ${lidar_length/2}" rpy="0 0 0" />
        <frame_name>laser_frame</frame_name>
    </xacro:lidar>

    <joint name="camera_joint" type="fixed">
        <parent link="base_link" />
        <child link="camera_link" />
        <origin
            xyz="0 0 0.168"
            ryp="0 0 0" />
    </joint>

    <link name="camera_link"></link>

    <xacro:depth_camera nameprefix="camera_1"
        parent="camera_link"
        camera_length="${intel_camera_length}"
        camera_width="${intel_camera_width}"
        camera_height="${intel_camera_height}"
        mass="${intel_camera_and_fixture_weight}"
        fixture_radius="${intel_camera_fixture_radius}"
        fixture_length="${intel_camera_fixture_length}">
        <origin xyz="0 0 ${intel_camera_fixture_length/2}" rpy="0 0 0" />
    </xacro:depth_camera>


</robot>